### ISSUE TITLE
Rename Fable.Import.{Library} to just Fable.{Library}?

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/fable-import#1]
Just a suggestion, looks cleaner IMO.

**Comment by alfonsogarciacaro** [comment]
I was considering this too, but I'd be in favour of keeping the `Fable.Import` prefix for several reasons:

- It's a way to group the bindings in this repo and it also makes it easier to list the bindings in Nuget search.
- Our goal must be to automate binding generation as much as possidireble, so `Fable.Import.` packages should be pure translations of the Typescript declaration files, while packages like `Fable.React` may include an opinionated layer to make interaction more idiomatic in F#.
- As commented in https://github.com/fable-compiler/Fable/pull/995, it can also be a way to identify bindings containing only metadata. This distinction is important because for libraries only with metadata (type definitions and attributes) Fable can reference directly the .dll as it doesn't need the source code. It's much faster for the F# compiler to read metadata in a .dll than parsing source code. We can take advantage of this fact and publish pure bindings without a `fable` folder containing the source code to speed up compilations.

**Comment by Zaid-Ajaj** [comment]
@alfonsogarciacaro Thanks for detailed answer, it makes sense, faster compilations is a big plus :+1: for fable apps
