### ISSUE TITLE
Architecture questions

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-import#2]
@alfonsogarciacaro I remember a discussion where you said something like that: 
> In fable-import we should have only bindings and not helpers in it

That's a good point but we can't assure that the bindings will not in the future come with helpers. That's things are discovered when using the API and we can't predict future :)

So will that be a problem if we start a binding here and finally some days/weeks later it will come with helpers in it.

Should we put the binding in this repo ? Have a separate repo ? Should I create it under my account ?

**Comment by alfonsogarciacaro** [comment]
I'd say the bindings should be pure translations of typescript declarations, mostly automated with ts2fable and with minimal manual editing (so it's easier to also automatically update them to latest versions). Helpers can go in a different library with a dependency on the binding. Actually I'm thinking of splitting the React binding from the helpers as well.

**Comment by MangelMaxime** [comment]
Don't you think we will start having a lot of dependencies in ours projects and having a bad time keeping all the version sync ?

**Comment by mike-morr** [comment]
What is the reason for keeping them separate?

**Comment by MangelMaxime** [comment]
@mike-morr Seems like we will not follow this away ( 👍 ). At least when you take a look at fable-react and fable-react-native repo they both contains all Helpers and Imports.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime @mike-morr I think I had the long explanation why we should distinguish bindings and helpers, but I cannot find it now so I'll write it again:

The way latest Fable version works with package references is this: look for the package location and check if there's a `fable` folder with the sources. If there's one, add a **project reference** to the main project so Fable can read the sources; if not, add a **dll reference** instead (Fable will only be able to read the metadata).

Fable needs the sources to compile actual code (basically method bodies) but can still read metadata (type declarations and attributes) from a dll. So in the case of bindings, it's enough to add the .dll to the package normally. This is easier for maintainers because they don't need to remember to add the sources to the package but, most importantly, it's much faster to just read a .dll than compiling source files, specially for big bindings. Compiling big files like Import.Browser or Import.Node may add around 5 seconds to the compilation, which is considerable.

Conceptually, I think the distinction is also important and it also exists in Typescript. The bindings would be _empty_ libraries, users know they're dealing directly with the JS libraries, while helpers are an intermediate layer between the JS library and the F# code.

**Comment by MangelMaxime** [comment]
I am closing as we agree now on the process :)
