### ISSUE TITLE
Should I just rename `PromiseLike` to `Promise`?

### ISSUE THREAD

**Issue by mrakgr** [fable-compiler/fable-import#93]
Since it is badly out of date I took the `Fable.Import.VSCode.fs` file and redid the Paket bindings and the reference by hand, but now all the `PromiseLike`s are type errors and the `Fable.Import.JS` where it has been is depreciated. I am new to Fable so I am not sure whether `PromiseLike` was supposed to be an alias or if it was a wholly different structure to `Promise`. What should I do here?

What I want to do is go through the [vscode-extension-samples](https://github.com/microsoft/vscode-extension-samples) and translate them to Fable from Typescript in order to get some practice for doing my own language plugin, but the bindings here are 3 years old and out of date so I am going to have to upgrade them along the way.

**Comment by MangelMaxime** [comment]
Hello @mrakgr ,

the history of `PromiseLike` is a bit special.

At first, `Promise` was not a standard in JavaScript but people from JavaScript made a sort of standard for it. This standard was more or less just a bunch of interfaces that had to be exposed if I remember correctly.

So TypeScript created the type `PromiseLike` in order to say, here I am expecting any implementation coming from a library or the native API which is compatible with `PromiseLike`. For example, when I looked at VSCode they were not using the `Promise` term but `Thenable` (if I remember correctly). But they are both more or less equivalent.

In the earlier, version of Fable, I think we made a distinction between `Promise` (the native implementation coming from the Brower for example) and `PromiseLike`. Now, we consider that you can use `Promise` as a replacement in the binding you are working on. In theory, it should work and make the life of everyone easier.

**Comment by mrakgr** [comment]
```
/**
 * Thenable is a common denominator between ES6 promises, Q, jquery.Deferred, WinJS.Promise,
 * and others. This API makes no assumption about what promise library is being used which
 * enables reusing existing code without migrating to a specific promise implementation. Still,
 * we recommend the use of native promises which are available in this editor.
 */
interface Thenable<T> {
	/**
	* Attaches callbacks for the resolution and/or rejection of the Promise.
	* @param onfulfilled The callback to execute when the Promise is resolved.
	* @param onrejected The callback to execute when the Promise is rejected.
	* @returns A Promise for the completion of which ever callback is executed.
	*/
	then<TResult>(onfulfilled?: (value: T) => TResult | Thenable<TResult>, onrejected?: (reason: any) => TResult | Thenable<TResult>): Thenable<TResult>;
	then<TResult>(onfulfilled?: (value: T) => TResult | Thenable<TResult>, onrejected?: (reason: any) => void): Thenable<TResult>;
}
```

Yeah, I see that this is defined at the very end of the at the very end of the definitions file for the `@types/vscode` module. Hmmm...I guess just swapping them with regular promises (assuming that is allowed) would make async code easier.

Looking at the TS type declarations file for the `@types/vscode` module, I see that it is 10k LOC most of which is comments. While in the Fable bindings it is only 860 LOC because most of that information has been cut out. Was that on purpose for some reason?

Also, how good are the automated tools for translating TS bindings to Fable ones? Looking at some of the old threads I saw one being mentioned. Is that something I should be looking into or would you recommend doing it by hand from where the previous author left off?

**Comment by mrakgr** [comment]
Also, do you have any advice for how to translate a complex type like than `Thenable` interface into F#?

**Comment by MangelMaxime** [comment]
You should try to use Promise directly instead of Thenable. That's what is already used in Ionide extension for example and that's works.

In order to convert d.ts you can use https://fable.io/ts2fable/. It is not perfect but does the 90-95% of the job for you.

**Comment by mrakgr** [comment]
I'll give it a shot. Thanks.
